name: "Update TopGit tree"

on:
  workflow_dispatch:
    inputs:
      keep_base_untouched:
        description: 'Set it to 1 to force a sync without updating the base from upstream'
        required: true
        default: '0'
      force_sync:
        description: 'Set it to 1 to force a sync even if net-next is not updated'
        required: true
        default: '0'

  schedule:
    - cron: '33 5 * * *' # in UTC: after US West coast's work day

jobs:
  export:
    if: github.repository_owner == 'multipath-tcp'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need all commits for TopGit
          token: '${{ secrets.PAT_JENKINS_TESSARES }}'
      - name: "Update TG tree"
        uses: multipath-tcp/mptcp-upstream-topgit-action@main
        with:
          not_base: "${{ github.event.inputs.keep_base_untouched || '0' }}"
          force_sync: "${{ github.event.inputs.force_sync || '0' }}"
